### PR TITLE
Add Youtube provider and expand tests for YouTube

### PR DESCRIPTION
**Pull request by Kuret**
Adds a separate provider for YouTube URLs, instead of using the generic one.
This skips the step that retrieved the `oembed_url` by going to the non-oembed url and getting it from the metadata, which saves an unneeded web request.

We had some trouble with the first phase (getting the oembed url by checking the oembed tag in the regular url), in which the server got an invalid response, this would happen randomly some time after we started the server.

There might be some rate limiting problems on large instances with many requests in a short amount of time from the same host. They might also detect the retrieval of the 'regular' youtube URL by the server with a non-standard UserAgent as a bot/crawler.

This makes it so the server only does 1 request to the `/oembed` json endpoint to get the embed information, and the client does 1 request to render the embed, whereas before the server did 2 requests, one of which wasn't intended to be retrieved programmatically.

This also adds some extra tests for the handling of various invalid urls.

### CODE REVIEW

**Comment by Kuret** [comment]
Regarding the sourcelevel-bot comments, I had a convoluted way of checking for a valid URL because I insisted on not using regex, but then I realized I had to check for playlists and the likes too and it would've gotten more complicated than a simple regex, so i changed it to a regex again and pushed over it.

**Comment by r8** [comment]
@Kuret Thank you very much for the contribution. I'm sorry about the delay on my end.

I've merged it, it should be on hex.pm in next few days, after I finish some of my in-progress stuff.

**Comment by Kuret** [comment]
@r8 any idea when you'll be able to put this on Hex.pm?

No rush, we'd just prefer the Hex package instead of a git branch in our `mix.exs`.

**Comment by r8** [comment]
hey @Kuret 
Well, I wanted to push a new version with some of my updates as well, but unfortunately COVID lockdown brought mess to my life and impacted my productity.
So I'll probably move my updates to the next version and will push to hex current stuff.

**Comment by Kuret** [comment]
Thanks for the reply, no worries and take care. And don't feel rushed, we're fine on the git branch for now.

**Comment by r8** [comment]
Thanks for your contribution and even more for your patience.
I've finally pushed it to hex.pm

**Pull request merged**
